### ISSUE TITLE
Error in locale de-DE

### ISSUE THREAD

**Issue by osebelin** [GothenburgBitFactory/holidata#103]
**Describe the bug**  
The `de-DE` data contains a typo in the ISO Code for the region "Bremen": The data uses `BH` but `HB` is correct 
(https://en.wikipedia.org/wiki/ISO_3166-2:DE).

**Expected behavior**  
The region code should be `HB`, e.g.
```
  holiday:
    locale: de-DE
    region: HB
    date: 2022-10-31
    description: Reformationstag
    type: RF
    notes:
```
